### ISSUE TITLE
plex server uri changed, cert cannot be validated

### ISSUE THREAD

**Issue by cbarbara** [vexorian/dizquetv#109]
don't know exactly when it happened, it might have been when i upgraded plex recently or maybe when my NAS needed a restart, or maybe this automatically happens behind the scenes ... but my plex server was given a new uri.

When dizquetv started it had this error in the logs on start:
> Couldn't get DVRS list from data. This error will prevent 'refresh guide' or 'refresh channels' from working for this Plex server. But it is NOT related to playback issues. Error: GET /livetv/drs failed: Hostname/IP does not match certificate's altnames: Host: 192-168-0-102.9d18b......plex.direct. is not in the cert's altnames: DNS:*.b5aaf7f4d......plex.direct 

It then had these more detailed errors when i visited the settings -> plex page.
```
Error getting Plex server status Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: 192-168-0-102.9d18b......plex.direct. is not in the cert's altnames: DNS:*.b5aaf7f4d......plex.direct
        at Object.checkServerIdentity (tls.js:288:12)
        at TLSSocket.onConnectSecure (_tls_wrap.js:1484:27)
        at TLSSocket.emit (events.js:310:20)
        at TLSSocket._finishInit (_tls_wrap.js:917:8)
        at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:687:12) {
  reason:     \"Host: 192-168-0-102.9d18b.......plex.direct. is not in the cert's altnames: DNS:*.b5aaf7f4d......plex.direct\",
  host:     '192-168-0-102.9d18b......plex.direct',
  cert: {
    subject: [Object: null prototype] {
      C:     'US',
      ST:     'California',
      L:     'Los Gatos',
      O:     'Plex, Inc.',
      CN:     '*.b5aaf7f4d......plex.direct'
    },
    issuer: [Object: null prototype] {
      C:     'US',
      O:     'Plex, Inc.',
      CN:     'Plex Devices High Assurance CA2'
    },
    subjectaltname:     'DNS:*.b5aaf7f4d......plex.direct',
    infoAccess: [Object: null prototype] {
          'OCSP - URI':     [Array],
          'CA Issuers - URI':     [Array]
    },
    modulus:     'BF884D0E855CA9D6D7865A4EA20AAB3017400736992D4D89F140D67498CF3BBAB70EEF04D0A6FE7E7016D8D32EC008E1336E31732454CCC9CA30D6DD8EEC8F2DF27A23C002C845A1228FBBF93C9F1E6B29115B2072FFE3E713B601E14A4921C8E5F88182B2FD172F967134706F6C1C654F4B1F3C733D5C52065079DE1948C6891C63016F143BABCE5CE46852B42CFBDBDA6912A7D4A310CEC62DBC73B7731E35E267EAF34647AAB149F94164AC04089F91A36A799B3AE84864C8444D0779534F82093991AE35F9FDAD634B5A0338CF5A72F4DE008005893737010586CAB9CC0D957815681561B3D0CE663E65B5825763D4AB93688A53307BFD3E6E99C88D07BD',
    bits:     2048,
    exponent:     '0x10001',
    pubkey: <Buffer 30 82 01 22 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 82 01 0f 00 30 82 01 0a 02 82 01 01 00 bf 88 4d 0e 85 5c a9 d6 d7 86 5a 4e a2 0a ab 30 17 ... 244 more bytes>,
    valid_from:     'Sep  1 00:00:00 2020 GMT',
    valid_to:     'Sep  1 12:00:00 2021 GMT',
    fingerprint:     '08:BE:5D:57:5E:9D:E2:97:35:F4:9F:15:6C:C7:9F:25:3F:2D:A4:E2',
    fingerprint256:     'B4:F9:5C:AB:60:D0:15:85:2C:ED:35:3C:5C:20:AE:E2:38:B5:8F:09:B8:A1:0F:07:3A:57:C1:88:3C:00:B9:8F',
    ext_key_usage: [     '1.3.6.1.5.5.7.3.1',     '1.3.6.1.5.5.7.3.2' ],
    serialNumber:     '07D09DE336F6B4241AA7819CFABBD4ED',
    raw: <Buffer 30 82 05 ef 30 82 04 d7 a0 03 02 01 02 02 10 07 d0 9d e3 36 f6 b4 24 1a a7 81 9c fa bb d4 ed 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 4c 31 0b ... 1473 more bytes>,
    issuerCertificate: {
      subject:     [Object: null prototype],
      issuer:     [Object: null prototype],
      infoAccess:     [Object: null prototype],
      modulus:     'A903EB8563615FE37FE4B2723CFB2F0D413D487FC5E7951C407171EDD4B0784467B69A8B5AF30BC9717B19A5FA19F3E7F5C6B99E245C62F63D5FA5F52D99AFCE5AE63A1D3D1A8E07CACCA617FF8A9D81C94B1597C14D6C3A607CBB422B7FCC28BDEB2D80D30975CFBD2AE3FE35411B53D757D412B110EB096C260FC3609E6E7AFB68B27A567EC05213764D40356DA7508D92B51F6B19768B3613FEB5966670647C3E35B42D546DD8AAA879E2744D10F740246837342F7BFD2EE9AC267017DC6AA3A569D4ABEBFE25C28642923985DD2C9F97FE400D66D9E7EAD6CFE0825F0B2D7F3D5A49236F2075CEBA277CEC7E956B2AEDCD4CE8548001984E76CBECD0990B',
      bits:     2048,
      exponent:     '0x10001',
      pubkey: <Buffer 30 82 01 22 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 82 01 0f 00 30 82 01 0a 02 82 01 01 00 a9 03 eb 85 63 61 5f e3 7f e4 b2 72 3c fb 2f 0d 41 ... 244 more bytes>,
      valid_from:     'May 19 12:00:00 2015 GMT',
      valid_to:     'May 19 12:00:00 2025 GMT',
      fingerprint:     '56:DD:60:95:42:6F:41:8F:C6:90:8B:FE:A3:C5:3E:20:39:FD:57:84',
      fingerprint256:     '50:D3:D7:1F:C0:CD:7E:36:AD:AE:32:22:1F:EF:BE:8C:C2:9B:26:76:BA:32:6C:09:B8:FA:1B:24:DB:E7:55:14',
      serialNumber:     '0DA3784D303377F0B50BCBCEDCAAA33A',
      raw: <Buffer 30 82 04 b9 30 82 03 a1 a0 03 02 01 02 02 10 0d a3 78 4d 30 33 77 f0 b5 0b cb ce dc aa a3 3a 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 6c 31 0b ... 1163 more bytes>,
      issuerCertificate:     [Object]
    }
  },
  code:     'ERR_TLS_CERT_ALTNAME_INVALID'
}
```

You can see the previously saved uri started with `9d18b` in the URL, but it now starts with `b5aaf7f4d`, so the code is not validating the cert with the old uri.
I had to manually edit the server uri to get things working again, and luckily checked the logs to notice these pretty obvious errors in the logs.

Do you know what actions trigger a plex server to use a new uri?

**Comment by vexorian** [comment]
It's a good question. I am not really sure. I think you'll have more luck asking in Plex-specific forums. I heard this is related to whole-server restarts.
