### ISSUE TITLE
Cannot use channels with periods in the number

### ISSUE THREAD

**Issue by jpann** [vexorian/dizquetv#153]
dizqueTV-backend 1.0.1
dizqueTV-ui 1.0.1

If you go to add a channel with a period in the channel number (e.g. 6.1) the channel will get created but the guide will lock up and no longer display any data. The xmltv file will display 'Error' when queried.

The file in the channels directory will get created (e.g. /channels/6.1.json).

Sample, redacted 6.1.json file:

`{"programs":[{"duration":600000,"isOffline":true}],"fillerContent":[],"fillerRepeatCooldown":1800000,"fallback":[],"icon":"http://LAN-IP:8087/images/dizquetv.png","disableFillerOverlay":true,"iconWidth":120,"iconDuration":60,"iconPosition":"2","startTime":"2020-10-05T20:00:00.000Z","offlinePicture":"http://LAN-IP:8087/images/generic-offline-screen.png","offlineSoundtrack":"","offlineMode":"pic","number":6.1,"name":"Channel 6.1","duration":600000}`

Log displays this when this happens:

`Unable to update internal guide data TypeError: Cannot read property 'number' of undefined
    at TVGuideService.buildItManaged (/home/node/app/src/tv-guide-service.js:278:41)
    at async TVGuideService.buildIt (/home/node/app/src/tv-guide-service.js:317:21)
    at async TVGuideService.buildIt (/home/node/app/src/tv-guide-service.js:324:7)
    at async TVGuideService.buildIt (/home/node/app/src/tv-guide-service.js:324:7)
    at async TVGuideService.buildIt (/home/node/app/src/tv-guide-service.js:324:7)
    at async TVGuideService.buildIt (/home/node/app/src/tv-guide-service.js:324:7)
    at async TVGuideService.buildIt (/home/node/app/src/tv-guide-service.js:324:7)
    at async TVGuideService.buildIt (/home/node/app/src/tv-guide-service.js:324:7)
    at async TVGuideService.buildIt (/home/node/app/src/tv-guide-service.js:324:7)
    at async TVGuideService.refresh (/home/node/app/src/tv-guide-service.js:46:9)
    at async Object.updateXML (/home/node/app/index.js:86:7)`

I have to manually remove the 6.1.json file to recover from this.

**Comment by MoRBiD-MaNGLeR** [comment]
Previously, if you tried to save a channel number outside of 1-1999, it wouldn't save.  This was changed to allow 1-4999 and it was confirmed that outside of 1-4999 still wouldn't save.  Something might have changed since then to allow non-integer values within 1-4999 to partially save.

Ideally, decimal channel numbers from 1-4999 should be supported.  If that is not the chosen direction, then minimally, the code needs to be reviewed to ensure that non-decimal channel numbers don't try to save at all.

Also, consider increasing channel range to 0-9999 inclusive.

**Comment by MoRBiD-MaNGLeR** [comment]
@vexorian I also added the BUG label because dizqueTV allowed @jpann to try to add a digital subchannel.  It errored out but it still renamed the JSON file.  Even if the enhancement is not pursued, dizqueTV should be fixed to disallow the file renaming.  I recommend we re-add BUG.

**Comment by MoRBiD-MaNGLeR** [comment]
#209 is a duplicate of #153.  Closing #209.

**Comment by ReenigneArcher** [comment]
xTeVe allows subchannels. Would be nice if we could set them up that way in dizquetv as well.

**Comment by kccorl1993** [comment]
Having this would allow a more seamless experience with locast2plex for those that use it.  Locast does decimal channel numbers and I would like to be able to insert my dizque lineup at a specific position and not scattered in between my Locast channels.

+1 for the feature request
