### ISSUE TITLE
ERR_STREAM_WRITE_AFTER_END

### ISSUE THREAD

**Issue by scoobshub** [vexorian/dizquetv#181]
**VERSION:** 1.2.1
Tonight this error kept happening on different channels, causing dizquetv to crash. Restarting dizquetv and re-playing the same channels solved the issue. I don't know if this is related to my setup or to the files being played; can you please help? Thanks!

Error output from console:
> Video and Audio are being transcoded by ffmpeg
> 
> Stream ended. Channel: 13 (itn | family)
> events.js:292
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error [ERR_STREAM_WRITE_AFTER_END]: write after end
>     at write_ (_http_outgoing.js:629:17)
>     at ServerResponse.write (_http_outgoing.js:621:15)
>     at Socket.ondata (_stream_readable.js:717:22)
>     at Socket.emit (events.js:315:20)
>     at addChunk (_stream_readable.js:295:12)
>     at readableAddChunk (_stream_readable.js:271:9)
>     at Socket.Readable.push (_stream_readable.js:212:10)
>     at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
> Emitted 'error' event on ServerResponse instance at:
>     at errorOrDestroy (internal/streams/destroy.js:108:12)
>     at ServerResponse.onerror (_stream_readable.js:753:7)
>     at ServerResponse.emit (events.js:315:20)
>     at writeAfterEndNT (_http_outgoing.js:684:7)
>     at processTicksAndRejections (internal/process/task_queues.js:85:21) {
>   code: 'ERR_STREAM_WRITE_AFTER_END'
> }

**Comment by vexorian** [comment]
It's likely related to the files you are playing AND it is a bug.

When there are issues playing some video, it's supposed to play the error stream. But in your case it is crashing.  Unfortunately, reproducing the issue will be hard. Unless you can pinpoint with a specific video or sequence of videos.

**Comment by scoobshub** [comment]
I'm afraid it's not related to a single file, because after restarting dizquetv when the crash happened the same channel started playing just fine. I'll keep a track if this happens again

**Comment by vexorian** [comment]
Enable ffmpeg logging so that next time it happens we have more information about the cause.

**Comment by scoobshub** [comment]
hi @vexorian, while doing some tests on the channel with time slot to replicate the flex issue, DizqueTV crashed again. I'm attaching the log if it can be of any help...
```
Press [q] to stop, [?] for help
Output #0, mpegts, to 'pipe:1':
  Metadata:
    service_provider: "dizqueTV"
    service_name    : "itn | christmas"
    encoder         : Lavf58.45.100
    Chapter #0:0: start 0.000000, end 66.901000
    Stream #0:0: Video: h264 (h264_videotoolbox), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 10000 kb/s, 25 fps, 90k tbn, 25 tbc (default)
    Metadata:
      encoder         : Lavc58.91.100 h264_videotoolbox
    Stream #0:1: Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      encoder         : Lavc58.91.100 ac3
There's a program with duration 0? 66596kB time=00:00:53.27 bitrate=10240.3kbits/s speed=0.997x    
Internal TV Guide data refreshed at 2020-11-5 21:45:50
XMLTV Updated at  2020-11-5 21:45:506173kB time=00:00:05.49 bitrate=9196.9kbits/s speed=0.727x     
frame= 2925 fps= 24 q=-0.0 size=  155418kB time=00:02:02.39 bitrate=10402.3kbits/s speed=0.999x    
Stream ended. Channel: 15 (itn | christmas)
Client Closed
Input #0, matroska,webm, from 'http://.../library/parts/36158/1604321100/file.mkv?X-Plex-Token':
  Metadata:
    title           : BaMax71
    creation_time   : 2019-12-07T05:53:35.000000Z
    ENCODER         : Lavf58.20.100
  Duration: 01:25:27.96, start: 0.000000, bitrate: 5075 kb/s
    Stream #0:0: Video: h264 (Main), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 180k tbc (default)
    Metadata:
      BPS             : 4177722
      BPS-eng         : 4177722
      DURATION        : 01:25:27.956000000
      DURATION-eng    : 01:25:27.956000000
      NUMBER_OF_FRAMES: 122948
      NUMBER_OF_FRAMES-eng: 122948
      NUMBER_OF_BYTES : 2677896970
      NUMBER_OF_BYTES-eng: 2677896970
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2019-12-07 05:53:35
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-12-07 05:53:35
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(ita): Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s (default)
    Metadata:
      title           : Surround
      BPS             : 448000
      BPS-eng         : 448000
      DURATION        : 01:25:27.392000000
      DURATION-eng    : 01:25:27.392000000
      NUMBER_OF_FRAMES: 160231
      NUMBER_OF_FRAMES-eng: 160231
      NUMBER_OF_BYTES : 287133952
      NUMBER_OF_BYTES-eng: 287133952
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2019-12-07 05:53:35
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-12-07 05:53:35
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s
    Metadata:
      title           : Surround
      BPS             : 448000
      BPS-eng         : 448000
      DURATION        : 01:25:27.904000000
      DURATION-eng    : 01:25:27.904000000
      NUMBER_OF_FRAMES: 160247
      NUMBER_OF_FRAMES-eng: 160247
      NUMBER_OF_BYTES : 287162624
      NUMBER_OF_BYTES-eng: 287162624
      _STATISTICS_WRITING_APP: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2019-12-07 05:53:35
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-12-07 05:53:35
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
http://192.168.1.187:8000/images/logo_itnxmas_snow.png: Immediate exit requested
Exiting normally, received signal 15.
Concat FFMPEG finished with code 255.
Stream FFMPEG exited with code 1.
Replacing failed stream with error streram

Video and Audio are being transcoded by ffmpeg
frame= 1573 fps= 21 q=-0.0 size=   53727kB time=00:01:03.48 bitrate=6933.1kbits/s speed=0.836x    
Stream ended. Channel: 15 (itn | christmas)
Concat FFMPEG finished with code 255.824kB time=00:02:02.93 bitrate=10383.3kbits/s speed=0.999x    
Client Closed
frame= 1577 fps= 21 q=-0.0 Lsize=   53755kB time=00:01:03.48 bitrate=6936.8kbits/s speed=0.832x    
video:50442kB audio:1488kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 3.515073%
Exiting normally, received signal 15.
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with Apple clang version 11.0.3 (clang-1103.0.32.62)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.3.1_1 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Stream FFMPEG finished with code 255.
Input #0, png_pipe, from 'http://localhost:8000/images/generic-error-screen.png':s speed=0.998x    
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: png, rgba(pc), 1920x1080 [SAR 3780:3780 DAR 16:9], 25 fps, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 (png) -> scale
  realtime -> Stream #0:0 (h264_videotoolbox)
  arealtime -> Stream #0:1 (ac3)
Press [q] to stop, [?] for help
Output #0, mpegts, to 'pipe:1':=  158720kB time=00:02:04.95 bitrate=10405.6kbits/s speed=0.998x    
  Metadata:
    service_provider: "dizqueTV"
    service_name    : "itn | christmas"
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (h264_videotoolbox), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 10000 kb/s, 24 fps, 90k tbn, 24 tbc
    Metadata:
      encoder         : Lavc58.91.100 h264_videotoolbox
    Stream #0:1: Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s
    Metadata:
      encoder         : Lavc58.91.100 ac3
events.js:292ps= 24 q=-0.0 size=  159343kB time=00:02:05.46 bitrate=10403.9kbits/s speed=0.998x    
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at write_ (_http_outgoing.js:629:17)
    at ServerResponse.write (_http_outgoing.js:621:15)
    at Socket.ondata (_stream_readable.js:717:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
Emitted 'error' event on ServerResponse instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at ServerResponse.onerror (_stream_readable.js:753:7)
    at ServerResponse.emit (events.js:315:20)
    at writeAfterEndNT (_http_outgoing.js:684:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
av_interleaved_write_frame(): Broken pipe   
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:1: Broken pipe
```

**Comment by scoobshub** [comment]
Happened again today at the end of an episode:

`=========================================================
! Start playback
! Channel: itn | comedy (2)
! Title: Sliptornado
! From : 0 to: 1291388
=========================================================
About to play plex stream
Plex transcoder initiated
Debug logging enabled
Getting stream
  deinterlace:     true
  streamPath:      plex
Direct play forced or native paths enabled
Recieved transcode decision:
{
  MediaContainer: {
    size: 1,
    allowSync: '1',
    identifier: 'com.plexapp.plugins.library',
    librarySectionID: '1',
    librarySectionTitle: 'Serie TV',
    librarySectionUUID: 'edd8adf5-1939-455c-a6c4-14158bcc0339',
    mdeDecisionCode: 1000,
    mdeDecisionText: 'Direct play OK.',
    mediaTagPrefix: '/system/bundle/media/flags/',
    mediaTagVersion: '1604451889',
    Metadata: [ [Object] ]
  }
}
Current video stats:
{
  duration: 1291967,
  anamorphic: false,
  pixelP: 1,
  pixelQ: 1,
  videoCodec: 'h264',
  videoWidth: '720',
  videoHeight: '400',
  videoFramerate: 24,
  videoDecision: 'copy',
  audioChannels: '2',
  audioCodec: 'ac3',
  audioDecision: 'copy'
}
{
  MediaContainer: {
    size: 1,
    allowSync: true,
    identifier: 'com.plexapp.plugins.library',
    librarySectionID: 1,
    librarySectionTitle: 'Serie TV',
    librarySectionUUID: 'edd8adf5-1939-455c-a6c4-14158bcc0339',
    mediaTagPrefix: '/system/bundle/media/flags/',
    mediaTagVersion: 1604451889,
    Metadata: [ [Object] ]
  }
}
Found audio index: 0
{
  directPlay: true,
  streamUrl: 'http://:32400/library/parts/31779/1586283526/file.mkv?X-Plex-Token=',
  streamStats: {
    duration: 1291967,
    anamorphic: false,
    pixelP: 1,
    pixelQ: 1,
    videoCodec: 'h264',
    videoWidth: '720',
    videoHeight: '400',
    videoFramerate: 24,
    videoDecision: 'copy',
    audioChannels: '2',
    audioCodec: 'ac3',
    audioDecision: 'copy',
    audioIndex: 0
  }
}
First stretch to 1920 x 1066. Then add padding to make it 1920 x 1080 
Stretch to 1920 x 1066. To fit target resolution of 1920 x 1080.
Video and Audio are being transcoded by ffmpeg
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with Apple clang version 11.0.3 (clang-1103.0.32.62)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.3.1_1 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, matroska,webm, from 'http://:32400/library/parts/31779/1586283526/file.mkv?X-Plex-Token=':
  Metadata:
    encoder         : libebml v1.3.7 + libmatroska v1.5.0
    creation_time   : 2019-06-03T18:46:14.000000Z
  Duration: 00:21:31.97, start: 0.000000, bitrate: 1443 kb/s
    Stream #0:0(ita): Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      BPS-eng         : 192000
      DURATION-eng    : 00:21:31.968000000
      NUMBER_OF_FRAMES-eng: 40374
      NUMBER_OF_BYTES-eng: 31007232
      _STATISTICS_WRITING_APP-eng: mkvmerge v34.0.0 ('Sight and Seen') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-06-03 18:46:14
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Video: h264 (High), yuv420p(progressive), 720x400 [SAR 80:81 DAR 16:9], SAR 79:80 DAR 711:400, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      BPS-eng         : 1250180
      DURATION-eng    : 00:21:31.958000000
      NUMBER_OF_FRAMES-eng: 30976
      NUMBER_OF_BYTES-eng: 201897648
      _STATISTICS_WRITING_APP-eng: mkvmerge v34.0.0 ('Sight and Seen') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-06-03 18:46:14
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Input #1, png_pipe, from 'http://:8000/images/logo_itncomedy.png':
  Duration: N/A, bitrate: N/A
    Stream #1:0: Video: png, rgba(pc), 466x125, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 (ac3) -> anull
  Stream #0:1 (h264) -> null
  Stream #1:0 (png) -> scale
  overlay -> Stream #0:0 (h264_videotoolbox)
  apad -> Stream #0:1 (ac3)
Press [q] to stop, [?] for help
Output #0, mpegts, to 'pipe:1':
  Metadata:
    service_provider: "dizqueTV"
    service_name    : "itn | comedy"
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (h264_videotoolbox), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 10000 kb/s, 23.98 fps, 90k tbn, 23.98 tbc (default)
    Metadata:
      encoder         : Lavc58.91.100 h264_videotoolbox
    Stream #0:1: Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      encoder         : Lavc58.91.100 ac3
There's a program with duration 0?588211kB time=00:21:01.17 bitrate=10316.2kbits/s speed=   1x     
There's a program with duration 0?
Internal TV Guide data refreshed at 2020-11-11 12:35:27
XMLTV Updated at  2020-11-11 12:35:27560kB time=00:21:01.65 bitrate=10314.6kbits/s speed=   1x    
frame=30976 fps= 24 q=-0.0 Lsize= 1626559kB time=00:21:31.96 bitrate=10313.6kbits/s speed=   1x    
video:1547976kB audio:30280kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 3.060491%
Stream FFMPEG exited normally.
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at write_ (_http_outgoing.js:629:17)
    at ServerResponse.write (_http_outgoing.js:621:15)
    at Socket.ondata (_stream_readable.js:717:22)
    at Socket.emit (events.js:315:20)
    at Socket.Readable.read (_stream_readable.js:506:10)
    at Socket.read (net.js:624:39)
    at flow (_stream_readable.js:1006:34)
    at resume_ (_stream_readable.js:987:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ServerResponse instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at ServerResponse.onerror (_stream_readable.js:753:7)
    at ServerResponse.emit (events.js:315:20)
    at writeAfterEndNT (_http_outgoing.js:684:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:1: Broken pipe
frame= 3505 fps=0.2 q=-0.0 Lsize=  182636kB time=00:02:26.26 bitrate=10229.0kbits/s speed=0.00929x    
video:173848kB audio:3428kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 3.023452%
Error writing trailer of pipe:1: Broken pipe
frame=  344 fps=0.0 q=-0.0 Lsize=   17148kB time=00:00:13.96 bitrate=10055.6kbits/s speed=0.000901x    
video:16374kB audio:327kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 2.678253%
Error writing trailer of pipe:1: Broken pipe
frame=   81 fps=0.0 q=-0.0 Lsize=    3764kB time=00:00:03.37 bitrate=9134.6kbits/s speed=0.000893x    
video:3593kB audio:79kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 2.520453%
Error writing trailer of pipe:1: Broken pipe
frame=17051 fps=1.1 q=-0.0 Lsize=  910112kB time=00:11:51.57 bitrate=10477.6kbits/s speed=0.046x    
video:866626kB audio:16678kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 3.034954%
Exiting normally, received signal 15.
Exiting normally, received signal 15.
Exiting normally, received signal 15.
av_interleaved_write_frame(): Broken pipe
Exiting normally, received signal 15.
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:1: Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
frame= 2519 fps=0.0 q=-0.0 Lsize=  131376kB time=00:01:45.42 bitrate=10208.5kbits/s speed=0.000712x    
video:124996kB audio:2470kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 3.066989%
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe`
