### ISSUE TITLE
Error: Request failed with status code 400

### ISSUE THREAD

**Issue by scoobshub** [vexorian/dizquetv#189]
Hi, on some movies i get this error but can't really understand why; the same content is available from Plex but if try to play the channel an error is generated...

Is it something wrong with the file/my setup? Thanks!

```
=========================================================
! Start playback
! Channel: itn | disney (14)
! Title: Herbie il maggiolino sempre più matto
! From : 2883104 to: 5309184
=========================================================
About to play plex stream
Plex transcoder initiated
Debug logging enabled
Getting stream
  deinterlace:     true
  streamPath:      plex
Direct play forced or native paths enabled
Error when attempting to play video. Fallback to error stream: Error: Request failed with status code 400
    at createError (/Users/miniserver/Documents/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/miniserver/Documents/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/miniserver/Documents/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
No duration found for error stream, using placeholder

Video and Audio are being transcoded by ffmpeg
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with Apple clang version 11.0.3 (clang-1103.0.32.62)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.3.1_1 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, lavfi, from 'color=c=black:s=1920x1080':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 (rawvideo) -> drawtext
  realtime -> Stream #0:0 (h264_videotoolbox)
  arealtime -> Stream #0:1 (ac3)
Press [q] to stop, [?] for help
[h264_videotoolbox @ 0x7f9a0a809e00] Color range not set for yuv420p. Using MPEG range.
Output #0, mpegts, to 'pipe:1':
  Metadata:
    service_provider: "dizqueTV"
    service_name    : "itn | disney"
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (h264_videotoolbox), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 10000 kb/s, 24 fps, 90k tbn, 24 tbc
    Metadata:
      encoder         : Lavc58.91.100 h264_videotoolbox
    Stream #0:1: Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s
    Metadata:
      encoder         : Lavc58.91.100 ac3
frame=   11 fps=0.0 q=-0.0 size=      17kB time=00:00:00.47 bitrate= 288.3kbits/frame=   24 fps= 23 q=-0.0 size=      42kB time=00:00:00.95 bitrate= 359.2kbits/frame=   36 fps= 23 q=-0.0 size=      65kB time=00:00:01.46 bitrate= 363.0kbits/frame=   48 fps= 23 q=-0.0 size=      89kB time=00:00:02.01 bitrate= 362.8kbits/frame=   61 fps= 24 q=-0.0 size=     115kB time=00:00:02.49 bitrate= 376.8kbits/frame=   73 fps= 24 q=-0.0 size=     139kB time=00:00:03.00 bitrate= 378.2kbits/frame=   85 fps= 24 q=-0.0 size=     162kB time=00:00:03.51 bitrate= 377.0kbits/frame=   98 fps= 24 q=-0.0 size=     187kB time=00:00:04.02 bitrate= 380.2kbits/frame=  110 fps= 24 q=-0.0 size=     211kB time=00:00:04.53 bitrate= 380.7kbits/frame=  122 fps= 24 q=-0.0 size=     234kB time=00:00:05.05 bitrate= 379.7kbits/frame=  134 fps= 24 q=-0.0 size=     258kB time=00:00:05.59 bitrate= 378.0kbits/frame=  147 fps= 24 q=-0.0 size=     283kB time=00:00:06.07 bitrate= 382.0kbits/frame=  159 fps= 24 q=-0.0 size=     306kB time=00:00:06.58 bitrate= 381.1kbits/frame=  171 fps= 24 q=-0.0 size=     330kB time=00:00:07.09 bitrate= 381.4kbits/frame=  184 fps= 24 q=-0.0 size=     361kB time=00:00:07.61 bitrate= 389.1kbits/frame=  196 fps= 24 q=-0.0 size=     386kB time=00:00:08.12 bitrate= 388.8kbits/frame=  208 fps= 24 q=-0.0 size=     409kB time=00:00:08.63 bitrate= 387.7kbits/frame=  220 fps= 24 q=-0.0 size=     433kB time=00:00:09.17 bitrate= 386.2kbits/frame=  233 fps= 24 q=-0.0 size=     458kB time=00:00:09.65 bitrate= 388.5kbits/frame=  245 fps= 24 q=-0.0 size=     481kB time=00:00:10.17 bitrate= 387.6kbits/frame=  257 fps= 24 q=-0.0 size=     505kB time=00:00:10.68 bitrate= 387.5kbits/frame=  270 fps= 24 q=-0.0 size=     530kB time=00:00:11.19 bitrate= 388.1kbits/frame=  282 fps= 24 q=-0.0 size=     554kB time=00:00:11.70 bitrate= 388.0kbits/frame=  294 fps= 24 q=-0.0 size=     578kB time=00:00:12.21 bitrate= 387.2kbits/frame=  306 fps= 24 q=-0.0 size=     602kB time=00:00:12.76 bitrate= 386.2kbits/frame=  319 fps= 24 q=-0.0 size=     627kB time=00:00:13.24 bitrate= 388.0kbits/frame=  331 fps= 24 q=-0.0 size=     650kB time=00:00:13.75 bitrate= 387.3kbits/frame=  343 fps= 24 q=-0.0 size=     674kB time=00:00:14.26 bitrate= 387.2kbits/frame=  356 fps= 24 q=-0.0 size=     699kB time=00:00:14.77 bitrate= 387.7kbits/frame=  368 fps= 24 q=-0.0 size=     724kB time=00:00:15.29 bitrate= 387.6kbits/frame=  380 fps= 24 q=-0.0 size=     747kB time=00:00:15.80 bitrate= 387.1kbits/frame=  392 fps= 24 q=-0.0 size=     771kB time=00:00:16.34 bitrate= 386.2kbits/frame=  405 fps= 24 q=-0.0 size=     796kB time=00:00:16.82 bitrate= 387.5kbits/frame=  417 fps= 24 q=-0.0 size=     819kB time=00:00:17.33 bitrate= 387.0kbits/frame=  429 fps= 24 q=-0.0 size=     843kB time=00:00:17.88 bitrate= 386.2kbits/frame=  442 fps= 24 q=-0.0 size=     869kB time=00:00:18.36 bitrate= 387.5kbits/frame=  454 fps= 24 q=-0.0 size=     893kB time=00:00:18.87 bitrate= 387.4kbits/frame=  466 fps= 24 q=-0.0 size=     916kB time=00:00:19.38 bitrate= 387.0kbits/frame=  478 fps= 24 q=-0.0 size=     940kB time=00:00:19.93 bitrate= 386.3kbits/frame=  491 fps= 24 q=-0.0 size=     965kB time=00:00:20.41 bitrate= 387.3kbits/s speed=0.996x    
Stream ended. Channel: 14 (itn | disney)
Client Closed
Concat FFMPEG finished with code 255.
```

**Comment by MoRBiD-MaNGLeR** [comment]
@scoobshub Do you have "Log FFMPEG to console" enabled in FFMPEG Settings?  Are you using dizqueTV 1.2.1?

**Comment by scoobshub** [comment]
@MoRBiD-MaNGLeR yes the log is enabled, yes i'm on version 1.2.1 and also yes the movie has duration value. Today this happened on another movie that always played without errors via DizqueTV; any clue?

Thanks a lot

```
=========================================================
! Start playback
! Channel: itn | cult (12)
! Title: Non c'è due senza quattro
! From : 5278279 to: 5974120
=========================================================
About to play plex stream
Plex transcoder initiated
Debug logging enabled
Getting stream
  deinterlace:     true
  streamPath:      plex
Direct play forced or native paths enabled
Error when attempting to play video. Fallback to error stream: Error: Request failed with status code 400
    at createError (/Users/miniserver/Documents/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/miniserver/Documents/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/miniserver/Documents/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
error: -4582438 ; undefined
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({ code: -1, cmd: 'error stream disabled. -4582438 undefined' })
    at FFMPEG.emit (events.js:304:17)
    at FFMPEG.spawnError (/Users/miniserver/Documents/dizquetv/src/ffmpeg.js:64:12)
    at OfflinePlayer.play (/Users/miniserver/Documents/dizquetv/src/offline-player.js:40:27)
    at /Users/miniserver/Documents/dizquetv/src/program-player.js:72:42
    at new Promise (<anonymous>)
    at ProgramPlayer.playDelegate (/Users/miniserver/Documents/dizquetv/src/program-player.js:70:18)
    at ProgramPlayer.play (/Users/miniserver/Documents/dizquetv/src/program-player.js:99:25)
    at ProgramPlayer.play (/Users/miniserver/Documents/dizquetv/src/program-player.js:119:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error when attempting to play video: Error: Additional error when attempting to play error stream.
    at ProgramPlayer.play (/Users/miniserver/Documents/dizquetv/src/program-player.js:107:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:518:11)
    at ServerResponse.header (/Users/miniserver/Documents/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/Users/miniserver/Documents/node_modules/express/lib/response.js:170:12)
    at /Users/miniserver/Documents/dizquetv/src/video.js:338:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Stream ended. Channel: 12 (itn | cult)
Concat FFMPEG exited normally.
Video queue exhausted. Either you played 100 different clips in a row or there were technical issues that made all of the possible 100 attempts fail.

```
