### ISSUE TITLE
New M3U error

### ISSUE THREAD

**Issue by chamby90** [vexorian/dizquetv#399]
I have been a proud DizqueTV user for a couple years now... and everything has been working great for a while.  However, just this morning, I started getting an M3U error and Im not sure why.  If I click on my M3U link and go to this page: http://127.0.0.1:8000/api/channels.m3u ... it just show "error" on the page. Im not even sure where to go next with this one.

Any suggestions?  Is this a new issue for everyone or just me? (i upgraded from v1.4.3 to 1.4.5 to see if that would fix the issue but no dice).

**Comment by vexorian** [comment]
could be anything

Best would be to monitor the logs and see what happens in the logs when you hit refresh

**Comment by chamby90** [comment]
@vexorian yeah... i should have posted that in my first message.  Here is the part of the log that I think is identifying the problem... i just have no idea what it means:

_**TypeError: Cannot read property 'stealth' of undefined
    at M3uService.buildM3uList (C:\dizquetv\src\services\m3u-service.js:51:23)
    at async C:\dizquetv\src\api.js:994:20**_

**Comment by vexorian** [comment]
there's something  wrong with your .dizquetv/channels folder.

One of the files is corrupted.

Most likely it's a file with 0 bytes in size.

Either way, this counts as a bug because dizqueTV is not handling the issue correctly. Tagging it as such.

If you have trouble finding the corrupted file, go to the discord and DM me about this (don't post the contents of your channels folder here, it would include your plex credentials)

**Comment by chamby90** [comment]
@vexorian yep... that was exactly it!  I recently added a dummy channel with just flex time so I could use the channel number in xteve for a different m3u8 stream.  I went into my channel folder, and although the file size was 1kb like my other dummy channels, when i opened it up, it was blank and had no content.   So I deleted the file and my issue is resolved!   Do you need any other information from me to help fix the bug?

**Comment by vexorian** [comment]
unfortunately there's not much we can do to figure out what happened that made it save only a blank channel. Maybe it crashed while saving it or something. But I will fix the code so that if this happens , at least it won't cause the rest of the service to fail.

**Comment by chamby90** [comment]
sounds good, thanks for following up on this so quickly!  I appreciate it
