### ISSUE TITLE
Not able to add content to  channels. 

### ISSUE THREAD

**Issue by DevXen** [vexorian/dizquetv#418]
So this is a strange issue. for the past few days i've been trying to either create new channels or add content to current channels. it loads the add content dialog just fine. it pulls the media from my plex. and i can add it to the bottom window. but when i click on done at the bottom to go back to the channel options. it just freezes. but this also stops my browser from transferring any data in any other tabs. i have to open task manager and end task on Firefox then restart it to use the browser again. so that's strange. and my tv channels all work just fine as they are. i just can't add or change the content on them.

i tried updating to the 1.5.0-Nvidia. thinking that might help. but it didn't. 

this was in my docker logs when i first started it up. it was in the 1.4.5 as well. partly why i thought i'd update to see if that would fix it.

`Open event channel.
Push event: Started building tv-guide at = Tue Apr 12 2022 22:21:59 GMT-0600 (Mountain Daylight Time)
Internal TV Guide data refreshed at 4/12/2022, 10:22:00 PM
Push event: Server Started
Error getting Plex server status Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: 172-17-0-1.c974f4913caa486295cf5b7f1462b887.plex.direct. is not in the cert's altnames: DNS:*.50bb7a82138c4194a688fc98f6eba132.plex.direct
at Object.checkServerIdentity (tls.js:288:12)
at TLSSocket.onConnectSecure (_tls_wrap.js:1484:27)
at TLSSocket.emit (events.js:310:20)
at TLSSocket._finishInit (_tls_wrap.js:917:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:687:12) {
reason: "Host: 172-17-0-1.c974f4913caa486295cf5b7f1462b887.plex.direct. is not in the cert's altnames: DNS:*.[Redacted].plex.direct",
host: '[Redacted].plex.direct',

subject: [Object: null prototype] {
CN: '*.[redacted].plex.direct'
},
issuer: [Object: null prototype] { C: 'US', O: "Let's Encrypt", CN: 'R3' },
subjectaltname: 'DNS:*.[redacted].plex.direct',
infoAccess: [Object: null prototype] {
'OCSP - URI': [Array],
'CA Issuers - URI': [Array]
},
modulus: 'DBFD6A02755392A80B41EF452E3023C956091E62C1C02FE9852D2E0BD623167B383398C76E131098B7A919CB313E3C4E7F63C95A61CBA81B051428042428219BA7124553651E42C9D68D4AABB517076AA8F3622D41CFCB3624C09E08C48CA161BE8C1E2952FCBC7A494198AE3227DB321190D23AC0D3710BF9614ABCCFC77A4D1501C4661FF2886B9332DC6FEF53FBFE19438966FC8309082221EDE1BFA27166E88DF197AA922E4D2543DA57A6E2B8E31D8430E097B3673951F4F1B94FB6DDA9DBAC948A28BE69A1156F14D13C32A39F0CC59BEBBD030C2A2A18F8EF16E34EBF6B4B36F2E33B31C93F129482BB38D07D6A73E07752941D0F1DF9DB9DEAC4B985',
bits: 2048,
exponent: '0x10001',
pubkey: <Buffer 30 82 01 22 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 82 01 0f 00 30 82 01 0a 02 82 01 01 00 db fd 6a 02 75 53 92 a8 0b 41 ef 45 2e 30 23 c9 56 ... 244 more bytes>,
valid_from: 'Apr 2 22:50:25 2022 GMT',
valid_to: 'Jul 1 22:50:24 2022 GMT',
fingerprint: '3B:1F:B7:E4:8D:DA:C2:8F:CC:04:14:C4:A4:22:7D:46:D3:7E:CC:82',
fingerprint256: '82:CA:A3:B5:DF:71:A0:9B:B9:EE:3B:3E:AF:39:AF:FA:78:FF:66:8B:10:8C:55:BF:E6:F9:0B:31:AA:76:EF:36',
ext_key_usage: [ '1.3.6.1.5.5.7.3.1', '1.3.6.1.5.5.7.3.2' ],
serialNumber: '038E0B5DD6F6C6682359C957B399899C53A1',
raw: <Buffer 30 82 05 62 30 82 04 4a a0 03 02 01 02 02 12 03 8e 0b 5d d6 f6 c6 68 23 59 c9 57 b3 99 89 9c 53 a1 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 32 ... 1332 more bytes>,
issuerCertificate: {
subject: [Object: null prototype],
issuer: [Object: null prototype],
infoAccess: [Object: null prototype],
modulus: 'BB021528CCF6A094D30F12EC8D5592C3F882F199A67A4288A75D26AAB52BB9C54CB1AF8E6BF975C8A3D70F4794145535578C9EA8A23919F5823C42A94E6EF53BC32EDB8DC0B05CF35938E7EDCF69F05A0B1BBEC094242587FA3771B313E71CACE19BEFDBE43B45524596A9C153CE34C852EEB5AEED8FDE6070E2A554ABB66D0E97A540346B2BD3BC66EB66347CFA6B8B8F572999F830175DBA726FFB81C5ADD286583D17C7E709BBF12BF786DCC1DA715DD446E3CCAD25C188BC60677566B3F118F7A25CE653FF3A88B647A5FF1318EA9809773F9D53F9CF01E5F5A6701714AF63A4FF99B3939DDC53A706FE48851DA169AE2575BB13CC5203F5ED51A18BDB15',
bits: 2048,
exponent: '0x10001',
pubkey: <Buffer 30 82 01 22 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 82 01 0f 00 30 82 01 0a 02 82 01 01 00 bb 02 15 28 cc f6 a0 94 d3 0f 12 ec 8d 55 92 c3 f8 ... 244 more bytes>,
valid_from: 'Sep 4 00:00:00 2020 GMT',
valid_to: 'Sep 15 16:00:00 2025 GMT',
fingerprint: 'A0:53:37:5B:FE:84:E8:B7:48:78:2C:7C:EE:15:82:7A:6A:F5:A4:05',
fingerprint256: '67:AD:D1:16:6B:02:0A:E6:1B:8F:5F:C9:68:13:C0:4C:2A:A5:89:96:07:96:86:55:72:A3:C7:E7:37:61:3D:FD',
ext_key_usage: [Array],
serialNumber: '912B084ACF0C18A753F6D62E25A75F5A',
raw: <Buffer 30 82 05 16 30 82 02 fe a0 03 02 01 02 02 11 00 91 2b 08 4a cf 0c 18 a7 53 f6 d6 2e 25 a7 5f 5a 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 4f 31 ... 1256 more bytes>,
issuerCertificate: [Object]
}
},
code: 'ERR_TLS_CERT_ALTNAME_INVALID'
}
XMLTV Updated at 4/12/2022, 10:22:56 PM
Push event: XMLTV updated at server time Tue Apr 12 2022 22:22:56 GMT-0600 (Mountain Daylight Time)`

at the end of the log it currently shows:

`at Plex.GetDVRS (/home/node/app/src/plex.js:147:13)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
Remove event channel.
Open event channel.
Remove event channel.
Open event channel.`

So yeah its a strange issue.

**Comment by zerojay** [comment]
Restart DizqueTV and try again.

**Comment by DevXen** [comment]
yeah I have. and i've restarted my server. but i'm guessing its a Firefox issue. as i was able to add and change channels in the edge browser just fine. just odd it would start with FF randomly. but thank you for your help. i'll just use edge to add/edit channels.
