### ISSUE TITLE
error playing files with no audio

### ISSUE THREAD

**Issue by wnypoker** [vexorian/dizquetv#422]
I have multiple channels set up and they are working great.

I have one channel in which the videos have no audio (screensaver videos).

I think it might be failing because there is no audio as the other channels and videos work.

All videos were transcoded using handbrake standard 1080p fast settings before being placed on plex.

----

Here is the log error message:

Stream starting. Channel: 13 (Aerial TV)
/stream audioOnly=false
=========================================================
! Start playback
! Channel: Aerial TV (13)
! Title: comp_HK_H004_C013_t9_6M_HB_tag0
! From : 374073 to: 660000
=========================================================
About to play plex stream
Channel is being played: 13
Video and Audio are being copied. ffmpeg is not transcoding.
Latency: (193
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'https://10-10-0-24.9771aaasfa3454250a30a47877e6c3695.plex.direct:32400/library/parts/355036/1656010341/file.mp4?X-Plex-Token=XXXXXXXXXXXX':
  Metadata:
    major_brand     : mp42
    minor_version   : 512
    compatible_brands: mp42iso2avc1mp41
    creation_time   : 2022-06-23T18:50:39.000000Z
    encoder         : HandBrake 20220401180027-d6a8916c4-master 2022040401
  Duration: 00:11:00.00, start: 0.000000, bitrate: 2419 kb/s
  Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 2416 kb/s, 26.41 fps, 30 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2022-06-23T18:50:39.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]

Stream map '0:a' matches no streams.

To ignore this, add a trailing '?' to the map.
Stream FFMPEG exited with code 1.
Replacing failed stream with error stream
error: oops ; oops
(node:23607) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pipe' of undefined
    at FFMPEG.<anonymous> (/home/prod/livetv/src/plex-player.js:136:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:23607) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by notanewbie** [comment]
I haven't checked my logs yet so I don't know if my issue is exactly the same, but I was able to get rid of these symptoms by getting rid of the timed video buffer.
